const DEFAULT_WOMAN='default-profile-woman.svg',DEFAULT_MAN='default-profile-man.svg';
function A(){return store.get('activePatientPhoto',DEFAULT_WOMAN)}
A.toString=A;
const LOGO='careloop-brand-emblem.png';
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v));queueSync(k)}};
let state={role:store.get('role','patient'),selectedRole:store.get('role','patient'),lang:store.get('lang','English'),q:{},qStep:0,assessment:[],game:null,authError:'',operationError:'',chat:store.get('chat',[{who:'ai',text:'Good morning, Amma. I am here with you. Would you like to start today’s memory activity?'}]),pending:store.get('pending',0),overviewLoading:false,overviewLoadedAt:0};
const firebaseExpected=!!(window.CARELOOP_FIREBASE_CONFIG?.apiKey&&!window.CARELOOP_FIREBASE_CONFIG.apiKey.startsWith('YOUR_'));
let authResolved=!firebaseExpected,authenticated=!firebaseExpected&&sessionStorage.getItem('careloopSession')==='yes';
const reminders=()=>store.get(patientKey('reminders'),[]);
const todayId=()=>new Date().toISOString().slice(0,10);
const waterCount=()=>store.get(`water:${currentPatientId()||'self'}:${todayId()}`,0);
function timeHasPassed(time){if(!time)return false;let [h,m]=time.split(':').map(Number),now=new Date();return now.getHours()*60+now.getMinutes()>=h*60+m}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const go=r=>{state.operationError='';state.operationErrorRoute='';location.hash=r};
function activePatient(){return store.get('activePatient',null)}
function currentPatientId(){return state.role==='patient'?(window.CareFirebase?.user?.uid||'self'):(activePatient()?.patientId||null)}
function patientKey(name){return `${name}:${currentPatientId()||'unselected'}`}
function queueSync(){if(!navigator.onLine){state.pending++;localStorage.setItem('pending',state.pending)}}
function toast(s){const t=document.querySelector('#toast');if(!t)return;clearTimeout(toast.timer);t.textContent=s;t.classList.add('show');toast.timer=setTimeout(()=>t?.classList.remove('show'),2600)}
function accountRoute(){return state.role==='caretaker'?'care-settings':state.role==='relative'?'relative-profile':state.role==='doctor'?'doctor-profile':'profile'}
const outlineIcon=name=>`<svg class="ui-icon" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
function header(title='',care=false){return `<header class="topbar"><div class="brand"><img src="${LOGO}" alt="Manomitra emblem"><div>Manomitra<small>✓ ${navigator.onLine?'Offline Ready':'Offline · saved locally'}</small></div></div>${title?`<strong>${title}</strong>`:''}<div class="header-actions"><button class="listen-button" aria-label="Read this screen aloud" title="Read this screen aloud" onclick="readCurrentPage()"><span>${outlineIcon('volume')}</span><small>Listen</small></button><button class="profile-button" aria-label="Open account profile" title="Open profile" onclick="go('${care?accountRoute():'profile'}')"><span class="account-initial">${esc((window.CareFirebase?.profile?.name||state.role||'U')[0].toUpperCase())}</span></button></div></header>`}
const nav=(active='home',care=false)=>{let items=state.role==='relative'?[['relative-dashboard','home','Home'],['care-progress','chart','Progress'],['assessment-reports','file','Reports'],['emergency-details','emergency','Emergency'],['relative-profile','user','Profile']]:state.role==='doctor'?[['health','home','Home'],['assigned-patients','people','Patients'],['health-trends','chart','Reports'],['health-alerts','bell','Alerts'],['doctor-profile','user','Profile']]:care?[['caregiver','home','Overview'],['patients','people','Patients'],['care-progress','chart','Reports'],['alerts','bell','Alerts'],['care-settings','settings','Settings']]:[['home','home','Home'],['games','puzzle','Games'],['chat','mic','Talk'],['reminders','clock','Reminders'],['profile','user','Profile']];return `<nav class="bottomnav" aria-label="Main navigation">${items.map(([r,i,l])=>`<a href="#${r}" aria-label="${l}" title="${l}" class="${active===r?'active':''}"><span aria-hidden="true">${outlineIcon(i)}</span><b>${l}</b></a>`).join('')}</nav>`}
function page(body,active,care=false,title=''){let showError=state.operationError&&state.operationErrorRoute===parseHash().route;return `<div class="shell">${header(title,care)}<main class="${care?'care-screen':'screen'}">${showError?`<div class="auth-error" role="alert"><b>Firebase action failed</b><p>${esc(state.operationError)}</p><button class="btn btn-ghost" onclick="state.operationError='';state.operationErrorRoute='';render()">Dismiss</button></div>`:''}${body}</main>${nav(active,care)}</div>`}
function operationFailed(error){state.operationError=friendlyAuthError(error);state.operationErrorRoute=parseHash().route;render();toast('Firebase action failed')}
function publicPage(body){return `<main class="public-shell"><section class="card" style="width:min(100%,520px)">${state.authError?`<div class="auth-error" role="alert"><b>Unable to continue</b><p>${esc(state.authError)}</p></div>`:''}${body}</section></main>`}
const back=(label='Back')=>`<button class="back" onclick="history.back()" aria-label="${label}">←</button>`;
const title=(t,s='')=>`<div class="section-title"><div><h1>${t}</h1>${s?`<p class="muted">${s}</p>`:''}</div></div>`;
function clearIcon(title){let t=title.toLowerCase(),icons=[['emergency','emergency'],['questionnaire','file'],['message','message'],['notification','bell'],['report','chart'],['progress','chart'],['history','clock'],['reminder','clock'],['game','puzzle'],['activit','target'],['stor','book'],['memor','book'],['chat','mic'],['talk','mic'],['patient','user'],['relative','people'],['doctor','people'],['setting','settings'],['language','globe'],['help','help'],['summary','brain'],['alert','bell'],['sync','cloud']];return icons.find(([word])=>t.includes(word))?.[1]||'target'}
const featureCard=(icon,t,d,r)=>`<button class="card feature-card" aria-label="${esc(t)}. ${esc(d)}. Tap to open." title="${esc(t)}" onclick="go('${r}')"><span class="icon" aria-hidden="true">${outlineIcon(clearIcon(t))}</span><span class="feature-copy"><h3>${t}</h3><p class="muted">${d}</p><strong class="tap-hint">Tap to open →</strong></span></button>`;

function welcome(){return publicPage(`<div class="center stack"><img class="splash-logo" src="${LOGO}" alt="CareLoop AI"><div><h1>CareLoop AI</h1><p class="muted">Gentle care. Familiar memories. Meaningful moments.</p></div><div class="avatar-options"><img src="${DEFAULT_MAN}" alt="Default older man profile"><img src="${DEFAULT_WOMAN}" alt="Default older woman profile"></div><button class="btn btn-primary" onclick="go('login')">Continue to Login →</button><p class="small muted">Supportive cognitive activities only · Not a medical diagnosis</p></div>`)}
function role(){return publicPage(`${back()}${title('Create an account','Choose the correct role.')}<div class="grid">${featureCard('♥','Patient signup','Requires a profile and invite created by a caretaker.','patient-signup')}${featureCard('🛡','Caretaker signup','Create patients and manage their care settings.','caretaker-signup')}${featureCard('⌂','Relative signup','Requires an invitation created by the caretaker.','relative-signup')}${featureCard('⚕','Doctor signup','Review assigned patient reports.','doctor-signup')}</div><a class="btn btn-ghost" href="#login">Already registered? Login</a>`)}
function chooseRole(role){state.selectedRole=role;go(`${role}-signup`)}
function login(){return publicPage(`<div class="center"><img class="splash-logo" src="${LOGO}" alt="Manomitra"><h1>Login to Manomitra</h1><p class="muted">Patient, caretaker, relative, and doctor accounts use this secure login.</p></div><form class="stack" onsubmit="auth(event,false)"><div class="field"><label>Email address</label><input name="email" type="email" required autocomplete="username" placeholder="name@example.com"></div><div class="field"><label>Password</label><input name="password" required type="password" minlength="6" autocomplete="current-password"></div><button class="btn btn-primary">Login</button></form><div class="stack"><a class="btn btn-ghost" href="#forgot">Forgot password?</a><a class="btn btn-secondary" href="#role">Create a new account</a></div>`)}
function registration(role){let labels={patient:'Patient',caretaker:'Caretaker',relative:'Relative',doctor:'Doctor'},extra=role==='patient'?`<div class="field"><label>Caretaker ID</label><input name="caretakerId" required placeholder="ID provided by caretaker"></div><div class="field"><label>Patient invite code</label><input name="inviteCode" required placeholder="PAT-XXXXXX"></div>`:['relative','doctor'].includes(role)?`<div class="field"><label>Caretaker invite code</label><input name="inviteCode" required placeholder="${role==='doctor'?'DOC':'REL'}-XXXXXX"></div>`:'';return publicPage(`${back()}${title(`${labels[role]} Signup`,role==='patient'?'Your caretaker must create your patient dashboard before you register.':['relative','doctor'].includes(role)?'Your caretaker must create this invitation first.':'Create a secure CareLoop account.')}<form class="stack" onsubmit="auth(event,true)"><input type="hidden" name="role" value="${role}"><div class="field"><label>Full name</label><input name="name" required autocomplete="name"></div>${extra}<div class="field"><label>Email address</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" required autocomplete="new-password"></div><button class="btn btn-primary">Create ${labels[role]} Account</button></form><p class="center">Already registered? <a class="skip" href="#login">Login</a></p>`)}
function patientSignup(){return registration('patient')}
async function auth(e,signup){e.preventDefault();state.authError='';let v=Object.fromEntries(new FormData(e.target)),role=v.role||'patient';try{let result;if(window.CareFirebase?.configured)result=signup?await CareFirebase.signUp(v):await CareFirebase.signIn(v.email,v.password);else if(firebaseExpected)throw new Error('Authentication service did not load. Check the internet connection and browser console.');else throw new Error('Authentication is unavailable.');role=signup?role:result?.profile?.role||role;authenticated=true;authResolved=true;state.role=role;store.set('role',role);let p=null;if(role==='patient'&&window.CareFirebase?.configured)p=await CareFirebase.loadOwnPatientProfile();else if(['relative','doctor'].includes(role)&&result?.profile?.patientId)p=await CareFirebase.loadPatientProfile(result.profile.patientId).catch(err=>{state.operationError=`Account created, but the patient profile could not be loaded: ${friendlyAuthError(err)}`;return null});if(p){if(role==='patient')store.set('profile',p);store.set('activePatient',p);store.set('activePatientPhoto',p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN);if(window.CareFirebase?.configured){let rs=await CareFirebase.loadReminders(p.patientId||window.CareFirebase.user?.uid).catch(()=>[]);store.set(patientKey('reminders'),rs)}}go(role==='caretaker'?'caregiver':role==='doctor'?'health':role==='relative'?'relative-dashboard':'home')}catch(err){state.authError=friendlyAuthError(err);render();toast('Authentication failed')}}
function friendlyAuthError(error){let c=error?.code||'',messages={'auth/invalid-credential':'Incorrect email or password.','auth/user-not-found':'No account exists for this email.','auth/wrong-password':'Incorrect password.','auth/email-already-in-use':'An account already exists for this email.','auth/weak-password':'Use a password with at least 6 characters.','auth/operation-not-allowed':'Enable Email/Password in Firebase Authentication.','auth/unauthorized-domain':'Add this domain under Authentication → Settings → Authorized domains.','auth/network-request-failed':'Firebase could not be reached. Check the internet connection.'};return messages[c]||error?.message||'Authentication failed. Please try again.'}
function forgot(){return publicPage(`${back()}${title('Reset your password','We will send a simple recovery link or code.')}<form class="stack" onsubmit="event.preventDefault();toast('Recovery instructions sent');go('login')"><div class="field"><label>Mobile number or email</label><input required></div><button class="btn btn-primary">Send recovery instructions</button></form>`)}
function language(settings=false){const langs=['English','हिन्दी (Hindi)','অসমীয়া (Assamese)','বাংলা (Bengali)','মৈতৈলোন্ (Manipuri)','खासी (Khasi)','Mizo ṭawng','नेपाली (Nepali)'];return page(`${back()}${title('Choose your language','You can change this any time. Voice support depends on your device.')}<div class="stack">${langs.map(l=>`<button class="choice ${state.lang===l?'selected':''}" onclick="setLang('${l.replace(/'/g,"\\'")}','${settings?'settings':'patient-setup'}')">${state.lang===l?'✓ ':''}${l}</button>`).join('')}</div>`,settings?'profile':undefined)}
function setLang(l,next){state.lang=l;store.set('lang',l);toast(`Language set to ${l}`);setTimeout(()=>go(next),300)}
function patientSetup(){return page(`${back()}${title('Tell us about you','This helps make Manomitra feel familiar and comfortable.')}<form class="stack" onsubmit="saveProfile(event)"><div class="field"><label>What should we call you?</label><input name="name" required></div><div class="field"><label>Age (optional)</label><input name="age" type="number"></div><div class="field"><label>Home city or village</label><input name="city"></div><div class="field"><label>Things you enjoy</label><textarea name="likes"></textarea></div><button class="btn btn-primary">Continue to gentle check-in →</button></form>`)}function saveProfile(e){e.preventDefault();store.set('profile',Object.fromEntries(new FormData(e.target)));go('questionnaire')}
function caregiverSetup(){return publicPage(`${back()}${title('Caregiver profile','Connect with care while respecting the patient’s dignity.')}<form class="stack" onsubmit="event.preventDefault();state.role='caregiver';store.set('role','caregiver');go('caregiver')"><div class="field"><label>Your name</label><input value="Priya" required></div><div class="field"><label>Relationship</label><select><option>Daughter</option><option>Son</option><option>Family caregiver</option><option>Nurse</option></select></div><div class="field"><label>Patient invite code</label><input value="KALYANI-72"></div><button class="btn btn-primary">Connect securely</button></form>`)}
function beginQuestionnaire(){state.assessment=[...window.QUESTION_BANK].sort(()=>Math.random()-.5).slice(0,9);state.q={};state.qStep=0;store.set('activeAssessment',state.assessment);go('questionnaire')}
function questionnaire(){if(!state.assessment.length)state.assessment=store.get('activeAssessment',[]);if(!state.assessment.length){state.assessment=[...window.QUESTION_BANK].sort(()=>Math.random()-.5).slice(0,9);store.set('activeAssessment',state.assessment)}let item=state.assessment[state.qStep];return page(`${back()}<p class="chip">${item.category} · Question ${state.qStep+1} of 9</p><div class="progress"><span style="width:${(state.qStep+1)/9*100}%"></span></div>${title(item.text,'There are no right or wrong answers. Choose what feels true today.')}<button class="btn btn-ghost" onclick="speak('${item.text.replace(/'/g,"\\'")}')">🔊 Read this question aloud</button><div class="stack">${item.options.map((o,i)=>`<button class="choice" onclick="answer('${item.id}',${i})"><span class="choice-number" aria-hidden="true">${i+1}</span><span>${o}</span></button>`).join('')}</div><p class="small muted center">Tap the answer that feels right. You can use 🔊 Listen if you want the screen read aloud.<br>This activity questionnaire is not a medical diagnosis.</p>`)}
function answer(id,value){state.q[id]=value;store.set('questionnaireDraft',state.q);if(++state.qStep>=9)submitAssessment();else render()}
async function submitAssessment(){let responses=state.assessment.map(q=>({questionId:q.id,category:q.category,question:q.text,answer:q.options[state.q[q.id]],value:state.q[q.id]})),result={responses,totalQuestions:9,score:responses.reduce((n,r)=>n+r.value,0),completedAt:new Date().toISOString()},key=patientKey('assessments'),all=store.get(key,[]);all.unshift(result);store.set(key,all);store.set('assessments',all);if(window.CareFirebase?.configured){try{await CareFirebase.saveAssessment(result)}catch(e){operationFailed(e);return}}store.set('activeAssessment',[]);go('questionnaire-result')}
function qResult(){let latest=store.get(patientKey('assessments'),[])[0],focus=[...new Set((latest?.responses||[]).filter(r=>r.value>0).map(r=>r.category))];return page(`${back()}${title('Your activity profile','Nine randomized questions completed and saved.')}<div class="card mint center"><span class="icon">✓</span><h2>Questionnaire complete</h2><p>Your responses help personalize activities and can be reviewed by your linked caretaker and doctor.</p></div><div class="card"><h2>Areas to focus on</h2><p>${focus.length?focus.map(x=>`<span class="chip">${x}</span>`).join(' '):'Maintaining memory, attention and daily routine.'}</p><div class="metric"><span>Questions answered</span><strong>9</strong></div><div class="metric"><span>Suggested session</span><strong>5 min</strong></div></div><button class="btn btn-primary" onclick="go('home')">Go to my home →</button><button class="btn btn-secondary" onclick="beginQuestionnaire()">Take a new random set</button><p class="small muted">CareLoop personalizes activities; it does not diagnose dementia, Alzheimer’s disease, or disease progression.</p>`)}

function home(){let rs=reminders(),waterReminder=true,water=waterCount(),p=store.get('profile',{}),now=new Date(),hour=now.getHours(),greeting=hour<12?'Good Morning':hour<17?'Good Afternoon':'Good Evening',date=now.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'}),time=now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}),name=p.name||'Patient',city=p.city||p.location||'your location',slots=['08:00','10:00','12:00','14:00','16:00','19:00'];return page(`${title(`${greeting}, ${esc(name)} ❤️`,`${date} · ${time} · ${esc(city)}`)}<div class="hero"><h2>Today’s Gentle Game</h2><p>Choose a familiar activity and take your time.</p><button class="btn btn-primary" onclick="startGame('memory')">▶ Start a Game</button></div><button class="card questionnaire-cta" onclick="beginQuestionnaire()"><span class="icon">☷</span><div><h2>Daily Questionnaire</h2><p>Answer 9 randomly selected questions.</p></div><span class="open-arrow">›</span></button><div class="section-title"><h2>Today’s Care</h2><a href="#reminders" class="skip">Manage</a></div>${rs.length?`<div class="stack">${rs.map(r=>`<div class="card"><div class="reminder"><div class="time">${esc(r.time)}</div><div><span class="chip">${esc(r.type)}</span><h3>${esc(r.title)}</h3><p class="small muted">${esc(r.note||'')}</p></div></div><button class="btn ${r.status==='done'?'btn-sage':'btn-ghost'}" ${!timeHasPassed(r.time)||r.status==='done'?'disabled':''} onclick="updateReminder('${r.id}','done')">${r.status==='done'?'✓ Completed':timeHasPassed(r.time)?'Mark as completed':'Available at '+esc(r.time)}</button></div>`).join('')}</div>`:'<div class="card empty"><h3>No reminders scheduled</h3><p>Your reminders will appear after you or your caretaker adds them.</p><a class="btn btn-primary" href="#add-reminder">＋ Add first reminder</a></div>'}${waterReminder?`<div class="card"><div class="section-title"><h3>Fresh Water</h3><b>${water} of 6 glasses</b></div><div class="water-row">${slots.map((t,i)=>`<button class="water-cup ${i<water?'done':''}" ${!timeHasPassed(t)||i<water?'disabled':''} onclick="drinkWater(${i+1})">${i<water?'✓':'○'}<small>${t}</small></button>`).join('')}</div><p class="small muted">Each water time becomes available only after that time has passed.</p></div>`:''}<div class="card" style="background:var(--primary);color:white"><h2>Talk to Manomitra</h2><p>Ask about today, family, or your activities.</p><button class="mic" style="width:74px;height:74px;border:7px solid white;font-size:30px" onclick="go('chat')">◉</button></div>`,'home')}
function drinkWater(n){let slots=['08:00','10:00','12:00','14:00','16:00','19:00'],slot=slots[n-1];if(!slot||!timeHasPassed(slot))return toast(`This glass can be marked after ${slot||'its scheduled time'}.`);let key=`water:${currentPatientId()||'self'}:${todayId()}`,current=waterCount(),next=Math.max(current,n);store.set(key,next);toast(`${next} of 6 glasses complete`);render()}function reminderCard(r){let canManage=['patient','caretaker'].includes(state.role);return `<div class="card reminder"><div class="time">${esc(r.time)}</div><div><span class="chip ${r.status==='done'?'good':r.status==='missed'?'warn':''}">${esc(r.type)}</span><h3>${esc(r.title)}</h3><p class="small muted">${esc(r.note||'')}</p></div>${canManage?`<button class="back" onclick="go('reminder-detail?id=${r.id}')" aria-label="Details">›</button>`:''}</div>`}
const gameTypes=[['memory','🌼','Memory Match','Pair familiar flowers and objects'],['attention','🎯','Attention Garden','Find the item that is different'],['pattern','◫','Pattern Path','Choose what comes next'],['object','☕','Object Recognition','Name familiar household items'],['routine','☀','Daily Routine Recall','Put everyday moments in order']];
function games(){return page(`${title('Gentle Activities','Choose one. Take your time, and pause whenever you wish.')}<div class="grid">${gameTypes.map(([r,i,t,d])=>featureCard(i,t,d,`game-intro?type=${r}`)).join('')}</div><div class="card soft"><h3>CareLoop personalization</h3><p>Current level: <b>${store.get('level',2)}</b>. Your next activity changes gently based on recent accuracy, response time, repeated mistakes and hints.</p></div><a class="btn btn-ghost" href="#progress">View my progress</a>`,'games')}
function gameIntro(type){const g=gameTypes.find(x=>x[0]===type)||gameTypes[0];return page(`${back()}<span class="chip good">Level ${store.get('level',2)} · AI personalized</span>${title(`${g[1]} ${g[2]}`,g[3])}<div class="card soft"><h2>How to play</h2><p>${type==='memory'?'Tap two cards to find matching pairs.':'Choose the answer that feels right. There is no timer and no pressure.'}</p><button class="btn btn-ghost" onclick="speak('Take your time. Choose the answer that feels right. There is no pressure.')">🔊 Listen to Instructions</button></div><button class="btn btn-primary" onclick="startGame('${type}')">Start activity →</button><button class="btn btn-ghost" onclick="go('games')">Choose another activity</button>`,'games')}
function startGame(type){state.game={type,start:Date.now(),attempts:0,hints:0,correct:0,total:type==='memory'?4:3,flipped:[],matched:[]};go('play')}
function play(){if(!state.game)return gameIntro('memory');let g=state.game;if(g.type==='memory'){const cards=['☕','🌼','🪔','🌸','☕','🌼','🪔','🌸'],names={'☕':'Filter Coffee · ಕಾಫಿ ಲೋಟ · कॉफ़ी','🌼':'Marigold / Genda · ಚೆಂಡು ಹೂ · गेंदा','🪔':'Diya / Deepa · ದೀಪ · दिया','🌸':'Lotus / Kamal · ಕಮಲ · कमल'};return page(`${back()}<span class="chip">No Timer · Zero Pressure</span>${title('Today’s Gentle Memory Match','Find matching pairs of familiar household and natural treasures. Take your time, Amma.')}<button class="btn btn-ghost" onclick="speak('Find matching pairs. Take your time, Amma.')">🔊 Listen to Instructions · ಕನ್ನಡ · हिंदी · English</button><div class="card mint"><h3>CareLoop AI Reassurance</h3><p>“Wonderful, Amma! You recognized the brass coffee tumbler right away. That warm filter coffee taste from Malleswaram!”</p></div><div class="game-grid">${cards.map((x,i)=>`<button class="game-card ${g.flipped.includes(i)||g.matched.includes(i)?'revealed':''}" onclick="flip(${i})"><span class="symbol">${g.flipped.includes(i)||g.matched.includes(i)?x:'∞'}</span>${g.flipped.includes(i)||g.matched.includes(i)?names[x]:'Tap to Turn · ಸ್ಪರ್ಶಿಸಿ · पलटें'}</button>`).join('')}</div><button class="btn btn-ghost" onclick="state.game.hints++;toast('Try the two warm drink cards')">💡 Need a Gentle Hint? We will highlight one friendly match</button><button class="btn btn-ghost" onclick="go('games')">☾ Pause / Take a Break</button><div class="card soft"><b>CareLoop Memory Personalization Engine</b><p>Active Deck: Curated from Amma’s personal photo archive and South Indian memory anchors (Bangalore and Chennai years).</p></div>`,'games')};let content={attention:['Which one is different?',['🌼 Flower','🌼 Flower','☕ Coffee'],2],pattern:['What comes next: 🌱 🌼 🌱 🌼 …',['🌱 Seedling','☕ Coffee','🪔 Lamp'],0],object:['What familiar object is this?  ☕',['Filter coffee','Flower garland','Prayer lamp'],0],routine:['What usually comes after waking up?',['Have breakfast','Go to bed','Evening walk'],0]}[g.type];return page(`${back()}<span class="chip">Question ${g.correct+1} of ${g.total}</span>${title(content[0],'Take your time. You can listen or ask for a hint.')}<button class="btn btn-ghost" onclick="speak('${content[0]}')">🔊 Listen</button><div class="stack">${content[1].map((o,i)=>`<button class="choice" onclick="gameAnswer(${i===content[2]})">${o}</button>`).join('')}</div><button class="btn btn-ghost" onclick="state.game.hints++;toast('Look for the most familiar choice')">💡 Gentle hint</button>`,'games')}
function flip(i){let g=state.game;if(g.flipped.includes(i)||g.matched.includes(i))return;g.flipped.push(i);g.attempts++;if(g.flipped.length===2){const cards=['☕','🌼','🪔','🌸','☕','🌼','🪔','🌸'],[a,b]=g.flipped;if(cards[a]===cards[b]){g.matched.push(a,b);g.correct++;g.flipped=[];toast('Wonderful — a match!');if(g.matched.length===8)setTimeout(finishGame,400)}else setTimeout(()=>{g.flipped=[];render()},700)}render()}
function gameAnswer(ok){let g=state.game;g.attempts++;if(ok){g.correct++;toast('Wonderful!')}else toast('That’s okay — let’s try gently.');if(g.attempts>=g.total)setTimeout(finishGame,350);else render()}
async function finishGame(){let g=state.game,time=Math.max(10,Math.round((Date.now()-g.start)/1000)),accuracy=Math.round(g.correct/g.total*100),old=store.get('level',2),next=accuracy>80&&g.hints<2?old+1:accuracy<50?Math.max(1,old-1):old,change=next>old?'slightly more challenging':next<old?'slightly easier':'at the same gentle level';store.set('level',next);let key=patientKey('sessions'),sessions=store.get(key,[]),report={patientId:currentPatientId(),type:g.type,score:g.correct,total:g.total,accuracy,responseTimeSeconds:time,difficulty:old,attempts:g.attempts,hintsUsed:g.hints,completionStatus:'completed',timestamp:new Date().toISOString(),nextDifficulty:next};sessions.unshift({...report,time,difficulty:old,hints:g.hints,status:'completed',next});store.set(key,sessions);store.set('lastResult',{...sessions[0],change});if(window.CareFirebase?.configured){try{await CareFirebase.saveGame(report)}catch(e){operationFailed(e);return}}go('game-result')}
function gameResult(){let r=store.get('lastResult',{});return page(`${title('Great Job! 🌟','Every gentle practice is meaningful.')}<div class="card mint center"><h2>You completed today’s activity</h2><p>You remembered or answered <b>${r.score||0} out of ${r.type==='memory'?4:3}</b>.</p></div><div class="card"><div class="metric"><span>Accuracy</span><strong>${r.accuracy||0}%</strong></div><div class="metric"><span>Response time</span><strong>${r.time||0}s</strong></div><div class="metric"><span>Hints used</span><strong>${r.hints||0}</strong></div><div class="metric"><span>Current level</span><strong>${r.difficulty||2}</strong></div><div class="metric"><span>Next level</span><strong>${r.next||2}</strong></div></div><div class="card soft"><h3>Why your next activity changed</h3><p>Based on accuracy, pace, attempts and hints, your next activity will be <b>${r.change||'at the same gentle level'}</b>.</p></div><button class="btn btn-primary" onclick="go('games')">Choose another activity</button><button class="btn btn-ghost" onclick="go('progress')">See progress</button>`,'games')}
function progress(care=false){let patient=activePatient(),ss=store.get(patientKey('sessions'),[]),avg=ss.length?Math.round(ss.reduce((a,b)=>a+b.accuracy,0)/ss.length):0,totalTime=Math.round(ss.reduce((n,s)=>n+(s.responseTimeSeconds||s.time||0),0)/60);return page(`${back()}${title(care?`${patient?.name||'Selected Patient'} — Progress`:'My Cognitive Activity Progress','Only completed activities for this patient are shown.')}${care?'<button class="btn btn-primary" onclick="loadCloudProgress()">Refresh This Patient’s Reports</button>':''}<div class="stat-grid"><div class="stat"><span>Sessions</span><b>${ss.length}</b></div><div class="stat"><span>Average accuracy</span><b>${avg}%</b></div><div class="stat"><span>Active time</span><b>${totalTime} min</b></div><div class="stat"><span>Trend</span><b>${ss.length<2?'Not enough data':avg>=75?'Steady':'Needs support'}</b></div></div><div class="card"><h2>Recent sessions</h2>${ss.length?ss.slice(0,20).map(s=>`<div class="metric"><span>${esc(s.type)} · ${new Date(s.timestamp).toLocaleDateString()}</span><strong>${s.accuracy}%</strong></div>`).join(''):'<p class="muted">No completed activities for this patient yet.</p>'}</div>`,care?'care-progress':'profile',care)}
async function loadCloudProgress(){try{let id=currentPatientId();if(!id)throw new Error('Select a patient first.');let reports=await CareFirebase.loadReports(id);store.set(patientKey('sessions'),reports.map(r=>({...r,time:r.responseTimeSeconds,difficulty:r.difficulty,hints:r.hintsUsed,status:r.completionStatus,next:r.nextDifficulty})));toast('Patient reports refreshed');render()}catch(e){operationFailed(e)}}

function chat(){return page(`${title('CareLoop Voice Companion','Speak naturally in your mother tongue. I am listening.')}<div class="actions"><span class="chip selected">✓ ${state.lang}</span><a class="chip" href="#language-settings">Change language</a></div><button class="mic" onclick="voiceInput()" aria-label="Tap to talk">🎙<span class="small" style="display:block">TAP & TALK</span></button><div class="card" id="chatlog">${state.chat.map(m=>`<div class="bubble ${m.who}"><b>${m.who==='ai'?'CareLoop Companion':'You'}</b><p>${esc(m.text)}</p>${m.who==='ai'?`<button class="btn btn-ghost" onclick="speak('${esc(m.text).replace(/'/g,"\\'")}')">🔊 Replay voice</button>`:''}</div>`).join('')}</div><form class="actions" onsubmit="sendChat(event)"><div class="field" style="flex:4"><label for="message">Your message</label><input id="message" required placeholder="Ask about today, family, or an activity"></div><button class="btn btn-primary btn-inline" style="align-self:end">Send</button></form><div class="section-title"><h2>Quick things to ask</h2></div><div class="stack">${['What medicine do I take now?','Play devotional songs','Show pictures of my grandchildren','Explain today’s game'].map(x=>`<button class="choice" onclick="quickChat('${x}')">${x} →</button>`).join('')}</div><button class="btn btn-secondary" onclick="go('chat-history')">Conversation history</button><button class="btn btn-danger" onclick="toast('Family and Nurse Lakshmi have been notified')">✱ Press for Family or Nurse Assistance</button><p class="small muted">CareLoop offers companionship and navigation help. It cannot diagnose, prescribe, change medication, or make emergency medical decisions.</p>`,'chat')}
function aiReply(q){let l=q.toLowerCase();if(l.includes('priya')||l.includes('arrive')||l.includes('barthale'))return 'Priya will visit at 5:00 PM for evening tea. She also called this morning to say she loves you.';if(l.includes('medicine'))return 'Your schedule says the next tablet check is at 1:00 PM. Please follow the label or ask Priya or Nurse Lakshmi if anything is unclear.';if(l.includes('grand'))return 'Arjun and Ananya are in Bengaluru. Would you like to open your family memories?';if(l.includes('game')||l.includes('activity'))return 'Tap two cards to find a pair. Take your time; there is no timer or pressure.';if(l.includes('doctor')||l.includes('dose')||l.includes('diagnos'))return 'I cannot diagnose or change medicine. I can help you contact Priya, Nurse Lakshmi, or your clinician.';return 'I am here with you, Amma. We can look at today’s routine, enjoy a memory, or begin a gentle activity.'}
function quickChat(x){let input=document.querySelector('#message');if(!input)return toast('Open the chat screen to enter a message.');input.value=x;input.focus()}
function sendChat(e){e.preventDefault();let i=e.target.querySelector('input'),q=i.value,userMessage={who:'user',text:q,timestamp:new Date().toISOString()};state.chat.push(userMessage);i.value='';store.set('chat',state.chat);if(window.CareFirebase?.configured)CareFirebase.saveChat(userMessage).catch(()=>{});render();setTimeout(()=>{let reply={who:'ai',text:aiReply(q),timestamp:new Date().toISOString()};state.chat.push(reply);store.set('chat',state.chat);if(window.CareFirebase?.configured)CareFirebase.saveChat(reply).catch(()=>{});render();toast('CareLoop replied')},650)}
function voiceInput(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice input is not supported on this browser. You can type below.');let input=document.querySelector('#message');if(!input)return toast('Open the chat screen before using voice input.');let r=new SR();r.lang=state.lang.includes('Hindi')?'hi-IN':'en-IN';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>toast('Listening…');r.onresult=e=>{let current=document.querySelector('#message'),text=e?.results?.[0]?.[0]?.transcript;if(!current||!text)return;current.value=text;current.dispatchEvent(new Event('input',{bubbles:true}));current.focus()};r.onerror=e=>{if(e?.error!=='aborted')toast('I could not hear that. Please try again.')};try{r.start()}catch{toast('Voice input is already active.')}}
function speak(text){if(!('speechSynthesis'in window))return toast('Read-aloud is unavailable on this device.');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));toast('Reading aloud')}
function readCurrentPage(){let main=document.querySelector('main'),text=main?.innerText?.replace(/Tap to open →/g,'')?.trim();if(!text)return toast('There is nothing to read on this screen.');speak(text)}
function chatHistory(manage=false){return page(`${back()}${title(manage?'Patient AI Chat History':'Conversation History',manage?'Only a linked caretaker may delete patient chat records.':'Patients and relatives cannot delete this safety record.')}<div class="stack">${state.chat.map(m=>`<div class="card"><b>${m.who==='ai'?'CareLoop':'Patient'}</b><p>${esc(m.text)}</p></div>`).join('')}</div>${manage?`<button class="btn btn-danger" onclick="caretakerDeleteChat()">Delete patient chat history</button>`:'<div class="card soft"><p>For continuity and safety, only your linked caretaker can delete this history.</p></div>'}`,manage?'caregiver':'chat',manage)}
async function caretakerDeleteChat(){if(state.role!=='caretaker')return toast('Only a caretaker can delete chat history.');if(!confirm('Delete the patient chat history? This cannot be undone.'))return;try{if(window.CareFirebase?.configured){let patientId=currentPatientId();if(!patientId)throw new Error('Select a patient first.');let messages=await CareFirebase.loadChat(patientId);await Promise.all(messages.map(m=>CareFirebase.deleteChat(patientId,m.id)))}state.chat=[];store.set('chat',[]);toast('Patient chat history deleted by caretaker.');render()}catch(e){toast(e.message)}}

function reminderList(){let rs=reminders();return page(`${title('Reminders','Medicine, hydration, activities and appointments for this patient.')}<div class="actions"><a class="btn btn-primary" href="#add-reminder">＋ Add reminder</a><button class="btn btn-ghost" onclick="loadPatientReminders()">↻ Refresh</button></div><div class="stack">${rs.length?rs.map(reminderCard).join(''):'<div class="card empty"><h2>No reminders yet</h2><p>Add only this patient’s actual medication, hydration or appointment reminders.</p></div>'}</div>`,state.role==='caretaker'?'care-reminders':'reminders',state.role==='caretaker')}
function reminderForm(edit=false,id){if(!['patient','caretaker'].includes(state.role))return empty('You cannot change reminders',dashboardForRole());let r=edit?reminders().find(x=>String(x.id)===String(id)):{};let care=state.role==='caretaker';return page(`${back()}${title(edit?'Edit Reminder':'Add Reminder','Use the patient’s actual reminder details.')}<form class="stack" onsubmit="saveReminder(event,'${edit?String(id):''}')"><div class="field"><label>Category</label><select name="type">${['Medicine','Hydration','Daily activity','Medical appointment'].map(x=>`<option ${r.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Reminder name</label><input name="title" required value="${esc(r.title||'')}"></div><div class="field"><label>Time</label><input name="time" type="time" required value="${esc(r.time||'')}"></div><div class="field"><label>Helpful note</label><textarea name="note">${esc(r.note||'')}</textarea></div><button class="btn btn-primary">Save reminder</button></form>${edit?`<button class="btn btn-danger" onclick="removeReminder('${r.id}')">Delete reminder</button>`:''}`,care?'care-reminders':'reminders',care)}
async function saveReminder(e,id){e.preventDefault();let rs=reminders(),v=Object.fromEntries(new FormData(e.target)),patientId=currentPatientId(),reminderId=id||String(Date.now()),item={...v,id:reminderId,status:id?(rs.find(x=>String(x.id)===String(id))?.status||'upcoming'):'upcoming'};if(!patientId)return operationFailed(new Error('Select a patient first.'));try{if(window.CareFirebase?.configured)await CareFirebase.saveReminder(patientId,item,reminderId);let i=rs.findIndex(x=>String(x.id)===reminderId);if(i>=0)rs[i]=item;else rs.push(item);store.set(patientKey('reminders'),rs);toast('Reminder saved for this patient');go(state.role==='caretaker'?'care-reminders':'reminders')}catch(err){operationFailed(err)}}
function reminderDetail(id){let r=reminders().find(x=>String(x.id)===String(id));if(!r)return empty('Reminder not found',state.role==='caretaker'?'care-reminders':'reminders');let ready=timeHasPassed(r.time),care=state.role==='caretaker';return page(`${back()}${title(esc(r.title),esc(r.type))}<div class="card"><div class="metric"><span>Time</span><strong>${esc(r.time)}</strong></div><div class="metric"><span>Status</span><span class="chip ${r.status==='done'?'good':'warn'}">${esc(r.status)}</span></div><p>${esc(r.note||'')}</p>${!ready?'<p class="small muted">This reminder can be completed only after its scheduled time.</p>':''}</div><button class="btn btn-sage" ${ready?'':'disabled'} onclick="updateReminder('${r.id}','done')">✓ Mark completed</button><button class="btn btn-secondary" onclick="go('edit-reminder?id=${r.id}')">Edit reminder</button><button class="btn btn-ghost" ${ready?'':'disabled'} onclick="updateReminder('${r.id}','missed')">Mark missed</button>`,care?'care-reminders':'reminders',care)}
async function removeReminder(id){if(!['patient','caretaker'].includes(state.role)||!confirm('Delete this reminder for this patient?'))return;try{let patientId=currentPatientId();if(window.CareFirebase?.configured)await CareFirebase.deleteReminder(patientId,String(id));store.set(patientKey('reminders'),reminders().filter(x=>String(x.id)!==String(id)));toast('Reminder deleted');go(state.role==='caretaker'?'care-reminders':'reminders')}catch(e){operationFailed(e)}}
async function updateReminder(id,status){let rs=reminders(),r=rs.find(x=>String(x.id)===String(id));if(!r||!timeHasPassed(r.time))return;try{r.status=status;if(window.CareFirebase?.configured)await CareFirebase.saveReminder(currentPatientId(),r,id);store.set(patientKey('reminders'),rs);toast(`Reminder marked ${status}`);render()}catch(e){operationFailed(e)}}
async function loadPatientReminders(){try{let id=currentPatientId();if(!id)throw new Error('Select a patient first.');let rs=await CareFirebase.loadReminders(id);store.set(patientKey('reminders'),rs);checkDueReminders();render()}catch(e){operationFailed(e)}}
async function requestReminderNotifications(){if(!('Notification'in window))return toast('Notifications are not supported on this device.');let permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();store.set('reminderNotifications',permission==='granted');if(permission==='granted'){unlockReminderAlarm();toast('Reminder notifications and alarm are enabled');showReminderNotification('Manomitra notifications enabled','You will receive reminder alerts with an alarm sound.','notification-test');checkDueReminders()}else toast('Allow notifications in device settings to receive reminders.')}
function unlockReminderAlarm(){try{let C=window.AudioContext||window.webkitAudioContext;if(!C)return;window.manomitraAudioContext=window.manomitraAudioContext||new C();window.manomitraAudioContext.resume()}catch{}}
function playReminderAlarm(){try{let C=window.AudioContext||window.webkitAudioContext,ctx=window.manomitraAudioContext||(C?new C():null);if(!ctx)return;ctx.resume();[0,.45,.9].forEach(delay=>{let oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;oscillator.type='sine';oscillator.frequency.value=880;gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(.28,start+.03);gain.gain.exponentialRampToValueAtTime(.001,start+.3);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.32)})}catch{}}
async function showReminderNotification(titleText,body,tag){playReminderAlarm();if(!('Notification'in window)||Notification.permission!=='granted')return;let options={body,icon:'careloop-brand-emblem.png',badge:'careloop-brand-emblem.png',tag,renotify:true,vibrate:[300,150,300,150,500],data:{url:'./#reminders'}};try{if('serviceWorker'in navigator){let registration=await navigator.serviceWorker.ready;await registration.showNotification(titleText,options)}else new Notification(titleText,options)}catch{}}
function reminderMinute(time){if(!/^\d{2}:\d{2}$/.test(time||''))return -1;let [h,m]=time.split(':').map(Number);return h*60+m}
function checkDueReminders(){if(state.role!=='patient'||!authenticated||!store.get('reminderNotifications',false))return;let now=new Date(),minute=now.getHours()*60+now.getMinutes(),day=todayId(),patient=currentPatientId()||'self',items=reminders().filter(r=>r.status!=='done').map(r=>({id:r.id,time:r.time,title:r.title,body:r.note||`${r.type} reminder`}));['08:00','10:00','12:00','14:00','16:00','19:00'].forEach((time,index)=>items.push({id:`water-${index}`,time,title:'Fresh Water Reminder',body:'It is time to drink a glass of water.'}));items.forEach(item=>{let due=reminderMinute(item.time),key=`reminderAlert:${patient}:${day}:${item.id}`;if(due>=0&&minute>=due&&minute<=due+2&&!store.get(key,false)){store.set(key,true);showReminderNotification(`Manomitra · ${item.title}`,`${item.body} Scheduled for ${item.time}.`,key)}})}

const memories=()=>store.get(patientKey('memories'),[]);
function memoryList(manage=false){let p=activePatient()||store.get('profile',{}),items=memories();return page(`${title(manage?`${esc(p.name||'Patient')} — Stories`:'Personal Stories','Familiar stories, people and moments kept close.')}<a class="btn btn-primary" href="#add-memory">＋ Add family story</a><div class="grid">${items.length?items.map(m=>`<button class="card" style="text-align:left" onclick="go('memory-detail?id=${m.id}')">${m.photoUrl?`<img src="${m.photoUrl}" class="photo" alt="${esc(m.title)}">`:''}<h3>${esc(m.title)}</h3><p class="muted">${esc(m.story)}</p></button>`).join(''):'<div class="card empty"><h2>No stories yet</h2><p>Add stories that belong specifically to this patient.</p></div>'}</div>`,manage?'caregiver':'profile',manage)}
function addMemory(){return page(`${back()}${title('Add a Personal Memory','A photo, a familiar voice, and a simple story can bring comfort.')}<form class="stack" onsubmit="saveMemory(event)"><div class="field"><label>Memory title</label><input name="title" required></div><div class="field"><label>Year or date</label><input name="date"></div><div class="field"><label>Story</label><textarea name="story" required></textarea></div><div class="field"><label>Photo (optional)</label><input type="file" accept="image/*"></div><div class="field"><label>Voice note (optional)</label><input type="file" accept="audio/*"></div><button class="btn btn-primary">Save memory</button></form><p class="small muted">Uploaded files are represented locally in this offline prototype; the story and details are stored on this device.</p>`,'profile')}
async function saveMemory(e){e.preventDefault();let ms=memories(),v=Object.fromEntries(new FormData(e.target)),story={...v,id:Date.now(),createdAt:new Date().toISOString()};ms.push(story);store.set(patientKey('memories'),ms);try{if(window.CareFirebase?.configured){let patientId=currentPatientId();if(!patientId)throw new Error('Select a patient first.');await CareFirebase.saveStory(story,patientId)}}catch(err){toast(err.message)}toast('Story saved for the patient');go(state.role==='caretaker'?'manage-memories':'memories')}
function memoryDetail(id){let m=memories().find(x=>x.id==id);if(!m)return empty('Memory not found','memories');return page(`${back()}${m.photoUrl?`<img src="${m.photoUrl}" class="hero-photo" alt="${esc(m.title)}">`:''}${title(esc(m.title),esc(m.date||''))}<div class="card"><p>${esc(m.story)}</p></div><button class="btn btn-primary" onclick="speak(decodeURIComponent('${encodeURIComponent(m.story||'')}'))">🎧 Listen to this story</button><button class="btn btn-secondary" onclick="toast('Family sharing link prepared')">Share with family</button>`,'profile')}
function profile(){let p=store.get('profile',{name:'Patient',age:'',city:''});return page(`${title('My Profile','Your choices, comfort and privacy.')}<div class="card patient-profile-head"><img src="${A}" class="patient-photo large-photo" alt="Patient profile"><div><h2>${esc(p.name||'Patient')}</h2><p>${esc(p.age||'Age not set')} · ${esc(p.city||'Location not set')}</p><span class="chip good">Connected to caretaker</span></div></div><div class="grid">${featureCard('✉','Message my caretaker','Leave a notification for help or support.','patient-message')}${featureCard('☷','Questionnaire','Start a random set or view saved reports.','patient-questionnaire')}${featureCard('↗','My progress','See my activity performance.','progress')}${featureCard('▣','My stories','Read familiar stories and memories.','memories')}${featureCard('☎','Emergency details','Contacts and essential care notes.','emergency-details')}${featureCard('⚙','Settings','Language, notifications and accessibility.','settings')}${featureCard('?','Help & Support','Simple guidance and contact options.','help')}</div><button class="btn btn-secondary" onclick="logout()">Sign out</button>`,'profile')}
function patientMessage(){let messages=store.get(patientKey('notifications'),[]).slice().reverse();return page(`${back()}${title('Message My Caretaker','Send a message and read your caretaker’s replies.')}<button class="btn btn-ghost" onclick="refreshOwnConversation()">↻ Refresh Conversation</button><div class="card conversation-messages">${messages.length?messages.map(n=>`<div class="conversation-bubble ${n.senderRole==='caretaker'?'from-caretaker':'from-patient'}"><b>${n.senderRole==='caretaker'?'Caretaker':'You'}</b><p>${esc(n.message)}</p><div class="message-meta"><span>${new Date(n.timestamp||Date.now()).toLocaleString()}</span><button type="button" class="listen-message" aria-label="Listen to this message" title="Listen to this message" onclick="speak(decodeURIComponent('${encodeURIComponent(n.message||'')}'))">${outlineIcon('volume')} Listen</button></div></div>`).join(''):'<p class="muted">No messages yet.</p>'}</div><form class="stack" onsubmit="savePatientMessage(event)"><div class="field"><label>Message for your caretaker</label><textarea name="message" required placeholder="For example: Please call me when you are free."></textarea></div><button class="btn btn-primary">Send to Caretaker</button></form>`,'profile')}
async function savePatientMessage(ev){ev.preventDefault();let message=new FormData(ev.target).get('message'),item={message,timestamp:new Date().toISOString(),senderRole:'patient',read:false};try{await CareFirebase.saveNotification(item);let own=store.get(patientKey('notifications'),[]);own.unshift(item);store.set(patientKey('notifications'),own);toast('Your caretaker will see this message');go('home')}catch(e){operationFailed(e)}}
async function refreshOwnConversation(){try{let notes=await CareFirebase.loadPatientNotifications(currentPatientId());store.set(patientKey('notifications'),notes);render()}catch(e){operationFailed(e)}}
function questionnaireHub(){return page(`${back()}${title('Questionnaire','Answer a new random set or review your earlier reports.')}<div class="grid">${featureCard('▶','Start 9 Questions','Questions are randomly selected from the question bank.','questionnaire')}${featureCard('☷','My Questionnaire Reports','See your scores, questions and selected answers.','my-assessment-reports')}</div>`,'profile')}
function patientAssessmentReports(){return assessmentReports(false)}
function careCircle(){let links=store.get('careLinks',[]);return page(`${back()}${title('My Care Circle','You control who can view your information.')}<button class="btn btn-primary" onclick="loadCareLinks()">Refresh connection requests</button><div class="stack">${links.length?links.map(l=>`<div class="card"><h3>${l.memberRole}</h3><p>Status: <span class="chip">${l.status}</span></p>${l.status==='pending'?`<div class="actions"><button class="btn btn-sage" onclick="reviewLink('${l.id}',true)">Approve</button><button class="btn btn-danger" onclick="reviewLink('${l.id}',false)">Reject</button></div>`:''}</div>`).join(''):'<div class="card empty"><p>No connection requests loaded.</p></div>'}</div><div class="card soft"><p>Share your connection code only with a trusted caretaker, relative, or doctor. They cannot see patient records until you approve them.</p></div>`,'profile')}
async function loadCareLinks(){try{let links=await CareFirebase.patientLinks();store.set('careLinks',links);toast('Care circle refreshed');render()}catch(e){toast(e.message)}}
async function reviewLink(id,ok){try{await CareFirebase.approveLink(id,ok);toast(ok?'Care member approved':'Request rejected');loadCareLinks()}catch(e){toast(e.message)}}
function emergencyDetails(manage=false){let e=store.get(patientKey('emergency'),{}),editable=state.role==='patient'||state.role==='caretaker',disabled=editable?'':'disabled';return page(`${back()}${title('Emergency Details','Essential information saved securely for this patient.')}<button class="btn btn-ghost" onclick="loadEmergencyDetails()">↻ Load Saved Details</button><form class="stack" onsubmit="saveEmergency(event)"><div class="field"><label>Primary emergency contact</label><input name="primaryName" required ${disabled} value="${esc(e.primaryName||'')}"></div><div class="field"><label>Primary phone</label><input name="primaryPhone" type="tel" required ${disabled} value="${esc(e.primaryPhone||'')}"></div><div class="field"><label>Secondary contact</label><input name="secondaryName" ${disabled} value="${esc(e.secondaryName||'')}"></div><div class="field"><label>Secondary phone</label><input name="secondaryPhone" type="tel" ${disabled} value="${esc(e.secondaryPhone||'')}"></div><div class="field"><label>Blood group</label><input name="bloodGroup" ${disabled} value="${esc(e.bloodGroup||'')}"></div><div class="field"><label>Allergies and important conditions</label><textarea name="allergies" ${disabled}>${esc(e.allergies||'')}</textarea></div><div class="field"><label>Preferred hospital</label><input name="hospital" ${disabled} value="${esc(e.hospital||'')}"></div><div class="field"><label>Emergency care notes</label><textarea name="notes" ${disabled}>${esc(e.notes||'')}</textarea></div>${editable?'<button class="btn btn-primary">Save emergency details</button>':''}</form>${e.primaryPhone?`<a class="btn btn-danger" href="tel:${esc(e.primaryPhone)}">☎ Call primary contact</a>`:''}`,manage?'caregiver':'profile',manage)}
async function loadEmergencyDetails(){try{let id=currentPatientId();if(!id)throw new Error('Select a patient first.');let data=await CareFirebase.loadEmergency(id);store.set(patientKey('emergency'),data||{});render()}catch(e){operationFailed(e)}}
async function saveEmergency(ev){ev.preventDefault();let v=Object.fromEntries(new FormData(ev.target)),patientId=currentPatientId();if(!patientId)return operationFailed(new Error('Select a patient first.'));try{if(window.CareFirebase?.configured)await CareFirebase.saveEmergency(v,patientId);store.set(patientKey('emergency'),v);toast('Emergency details saved securely');render()}catch(e){operationFailed(e)}}
function settings(){return page(`${back()}${title('Settings','Make CareLoop comfortable for you.')}<div class="stack">${featureCard('文','Language',state.lang,'language-settings')}${featureCard('🔔','Notifications','Sounds, vibration and caregiver alerts.','notification-settings')}${featureCard('☁','Offline & Sync',`${state.pending} changes waiting to sync.`,'sync')}<div class="card"><div class="metric"><span>Extra large text</span><button class="toggle" onclick="this.classList.toggle('on');document.documentElement.style.fontSize=this.classList.contains('on')?'21px':'18px'"></button></div><div class="metric"><span>Reduced motion</span><button class="toggle on" onclick="this.classList.toggle('on')"></button></div><div class="metric"><span>High contrast</span><button class="toggle" onclick="this.classList.toggle('on');document.body.style.filter=this.classList.contains('on')?'contrast(1.15)':'none'"></button></div></div></div>`,'profile')}
function notificationSettings(){let enabled=store.get('reminderNotifications',false)&&window.Notification?.permission==='granted';return page(`${back()}${title('Notification Settings','Enable mobile reminder alerts and alarm sound.')}<div class="card"><div class="metric"><span>Reminder notifications</span><strong>${enabled?'Enabled':'Not enabled'}</strong></div><p class="muted">Allow notifications so medicine, appointment, activity and Fresh Water reminders can alert you at their scheduled time.</p><button class="btn btn-primary" onclick="requestReminderNotifications()">${enabled?'Test / Re-enable Notifications':'Enable Notifications & Alarm'}</button></div><div class="card soft"><p class="small">Keep Manomitra installed or open for browser-based scheduled checks. The final APK will use Android native local notifications for reliable alarms when the app is fully closed.</p></div>`,'profile')}
function help(){return page(`${back()}${title('Help & Support','Simple help is always within reach.')}<div class="stack">${featureCard('▶','How to play activities','There is no timer. Pause whenever you like.','game-intro?type=memory')}${featureCard('🎙','How to use voice','Tap the large microphone and speak naturally.','chat')}<button class="btn btn-primary" onclick="toast('Calling daughter Priya…')">☎ Call daughter Priya</button><button class="btn btn-secondary" onclick="toast('Calling Nurse Lakshmi…')">☎ Call Nurse Lakshmi</button><button class="btn btn-danger" onclick="toast('Emergency services call requested')">Emergency assistance</button></div><div class="card soft"><h3>Important</h3><p>CareLoop supports routines and activities. For medical questions, changes in condition, or emergencies, contact a qualified professional or emergency service.</p></div>`,'profile')}
function syncPage(){return page(`${back()}${title('Offline & Sync Status','Your supported activities work even without internet.')}<div class="card center"><span class="icon">${navigator.onLine?'☁✓':'☁'}</span><h2>${navigator.onLine?'Sync complete ✓':'You are offline'}</h2><p>${state.pending} activities waiting to sync.</p></div><div class="card"><p>✓ Cached pages and personal details</p><p>✓ Games available offline</p><p>✓ Questionnaire and results saved locally</p><p>✓ Reminder status queued safely</p></div><button class="btn btn-primary" onclick="syncNow()">Sync now</button>`,'profile')}
function syncNow(){if(!navigator.onLine)return toast('Still offline. We will sync when internet returns.');state.pending=0;localStorage.setItem('pending','0');toast('Sync complete ✓');render()}

function createPatient(){return page(`${back()}${title('Create Patient Dashboard','Complete this before the patient creates an account.')}<form class="stack" onsubmit="savePatientDraft(event)"><div class="field"><label>Patient full name</label><input name="name" required></div><div class="actions avatar-choice"><label class="choice"><input type="radio" name="defaultAvatar" value="${DEFAULT_WOMAN}" checked><img src="${DEFAULT_WOMAN}" alt="Default older woman avatar"><span>Woman avatar</span></label><label class="choice"><input type="radio" name="defaultAvatar" value="${DEFAULT_MAN}"><img src="${DEFAULT_MAN}" alt="Default older man avatar"><span>Man avatar</span></label></div><div class="field"><label>Or upload patient photo</label><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"><small>The image is compressed and saved in the patient’s Firestore profile. Firebase Storage is not required.</small></div><div class="field"><label>Age</label><input name="age" type="number" min="40" max="120"></div><div class="field"><label>City or village</label><input name="city"></div><div class="field"><label>Support notes</label><textarea name="notes"></textarea></div><button class="btn btn-primary">Create Dashboard & Invite</button></form>`,'patients',true)}
async function compressProfilePhoto(file){if(!file?.size)return null;if(file.size>8*1024*1024)throw new Error('Choose an image smaller than 8 MB.');let bitmap=await createImageBitmap(file),scale=Math.min(1,512/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.72)}
async function savePatientDraft(ev){ev.preventDefault();state.operationError='';let fd=new FormData(ev.target),file=fd.get('photo'),data={name:fd.get('name'),age:fd.get('age'),city:fd.get('city'),notes:fd.get('notes'),defaultAvatar:fd.get('defaultAvatar')};try{if(file?.size)data.photoData=await compressProfilePhoto(file);let created=await CareFirebase.createPatientProfile(data),list=store.get('caretakerPatients',[]);list.push({...data,photoData:null,...created,status:'awaiting_patient_signup'});store.set('caretakerPatients',list);store.set('activePatientPhoto',created.photoUrl);toast('Patient dashboard created');go(`patient-invite?id=${created.id}`)}catch(e){operationFailed(e)}}
function patientInvite(id){let p=store.get('caretakerPatients',[]).find(x=>x.id===id);if(!p)return empty('Patient invitation not found','patients');return page(`${back()}${title('Patient Dashboard Created','Give both details below directly to the patient.')}<div class="card center"><img class="avatar" style="width:100px;height:100px" src="${p.photoUrl}"><h2>${esc(p.name)}</h2><div class="metric"><span>Caretaker ID</span><strong class="code-text">${esc(p.caretakerId)}</strong></div><div class="metric"><span>Patient invite code</span><strong>${esc(p.code)}</strong></div></div><button class="btn btn-primary" onclick="navigator.clipboard?.writeText('${esc(p.caretakerId)} / ${esc(p.code)}');toast('Invite details copied')">Copy Invite Details</button><p class="small muted">The patient must enter the matching caretaker ID and patient invite code on Patient Signup.</p>`,'patients',true)}
function createRelative(memberRole='relative',selectedPatientId=''){let ps=store.get('caretakerPatients',[]).filter(p=>p.status==='active'&&p.patientId),isDoctor=memberRole==='doctor',label=isDoctor?'Doctor':'Relative';return page(`${back()}${title(`Invite ${label}`,`Connect a ${label.toLowerCase()} to one particular patient.`)}<form class="stack" onsubmit="saveRelativeInvite(event)"><div class="field"><label>Patient</label><select name="patientId" required>${ps.map(p=>`<option value="${p.patientId}" ${String(p.patientId)===String(selectedPatientId)?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><input type="hidden" name="memberRole" value="${memberRole}"><div class="field"><label>${label} name</label><input name="name" required></div><div class="field"><label>${label} email</label><input name="email" type="email" required></div><button class="btn btn-primary" ${ps.length?'':'disabled'}>Create ${label} Invitation</button></form>${ps.length?'':'<div class="card peach"><p>The patient must complete signup before you can create this connection.</p></div>'}`,'patients',true)}
async function saveRelativeInvite(ev){ev.preventDefault();state.operationError='';let v=Object.fromEntries(new FormData(ev.target));try{let code=await CareFirebase.createRelativeInvite(v.patientId,v.name,v.email,v.memberRole);store.set('lastRelativeInvite',{...v,code});toast(`${v.memberRole==='doctor'?'Doctor':'Relative'} invite created: ${code}`);go('relative-invite')}catch(e){operationFailed(e)}}
function relativeInvite(){let i=store.get('lastRelativeInvite',{}),isDoctor=i.memberRole==='doctor',label=isDoctor?'Doctor':'Relative';return page(`${back()}${title(`${label} Invitation Ready`,`Send this code privately to the ${label.toLowerCase()}.`)}<div class="card center"><h2>${esc(i.name||label)}</h2><p>${label} signup code</p><strong class="invite-code">${esc(i.code||'Not created')}</strong><p class="small muted">This invitation connects only to the selected patient.</p></div><button class="btn btn-primary" onclick="navigator.clipboard?.writeText('${esc(i.code)}');toast('Code copied')">Copy Code</button>`,'patients',true)}
function caretakerPatientSettings(){let s=store.get('patientSettings',{language:'English',largeText:true,voice:true,notifications:true,difficulty:2});return page(`${back()}${title('Patient Settings','Change these when the patient needs assistance.')}<form class="stack" onsubmit="saveCaretakerSettings(event)"><div class="field"><label>Language</label><select name="language"><option>${s.language}</option><option>Hindi</option><option>Kannada</option><option>Assamese</option></select></div><div class="field"><label>Activity difficulty</label><select name="difficulty"><option value="1">Gentle 1</option><option value="2" selected>Gentle 2</option><option value="3">Gentle 3</option></select></div>${['largeText|Extra-large text','voice|Voice guidance','notifications|Reminder notifications'].map(x=>{let [n,l]=x.split('|');return `<label class="choice"><input type="checkbox" name="${n}" ${s[n]?'checked':''}> ${l}</label>`}).join('')}<button class="btn btn-primary">Save Patient Settings</button></form>`,'care-settings',true)}
async function saveCaretakerSettings(ev){ev.preventDefault();let f=new FormData(ev.target),v={language:f.get('language'),difficulty:Number(f.get('difficulty')),largeText:f.has('largeText'),voice:f.has('voice'),notifications:f.has('notifications')};store.set('patientSettings',v);try{if(window.CareFirebase?.configured){let patientId=currentPatientId();if(!patientId)throw new Error('Select a patient first.');await CareFirebase.savePatientSettings(patientId,v)}toast('Patient settings updated')}catch(e){toast(e.message)}}
function patientConversation(p,notes){let messages=notes.filter(n=>n.patientId===p.patientId&&String(n.message||'').trim()).slice().reverse();if(!messages.length)return '';let unread=messages.filter(n=>n.senderRole!=='caretaker'&&!n.read).length;return `<section class="card conversation-card"><div class="patient-summary conversation-head"><img src="${p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN}" class="patient-photo" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p class="muted">${messages.length} message${messages.length===1?'':'s'}</p></div>${unread?`<span class="chip warn">${unread} new</span>`:'<span class="chip good">Replied</span>'}</div><div class="conversation-messages">${messages.length?messages.map(n=>`<div class="conversation-bubble ${n.senderRole==='caretaker'?'from-caretaker':'from-patient'}"><b>${n.senderRole==='caretaker'?'You':'Patient'}</b><p>${esc(n.message)}</p><div class="message-meta"><span>${new Date(n.timestamp||Date.now()).toLocaleString()}</span><button type="button" class="listen-message" aria-label="Listen to this message" title="Listen to this message" onclick="speak(decodeURIComponent('${encodeURIComponent(n.message||'')}'))">${outlineIcon('volume')} Listen</button></div></div>`).join(''):'<p class="muted">No messages yet.</p>'}</div><form class="reply-form" onsubmit="replyToPatient(event,'${p.patientId}')"><label for="reply-${p.patientId}">Reply to ${esc(p.name)}</label><div class="actions"><input id="reply-${p.patientId}" name="message" required placeholder="Type a helpful reply"><button class="btn btn-primary btn-inline">Reply</button></div></form></section>`}
function caregiver(){let patients=store.get('caretakerPatients',[]),notes=store.get('careNotifications',[]),conversationPatients=patients.filter(p=>p.patientId&&notes.some(n=>n.patientId===p.patientId&&String(n.message||'').trim())),unread=notes.filter(n=>String(n.message||'').trim()&&n.senderRole!=='caretaker'&&!n.read).length;return page(`${title('Caretaker Overview','Select a patient to open their individual care profile.')}<div class="actions"><a class="btn btn-primary" href="#create-patient">＋ Create Patient</a><a class="btn btn-secondary" href="#create-relative">＋ Invite Relative</a><button class="btn btn-ghost" onclick="loadCaretakerOverview()">↻ Refresh</button></div><section><div class="section-title"><h2>My Patients</h2><span class="chip">${patients.length}</span></div><div class="patient-card-grid">${patients.length?patients.map(p=>`<div class="card patient-manage-card patient-showcase-card"><button class="patient-open" onclick="selectPatient('${p.id}')"><img src="${p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN}" class="patient-photo" alt="${esc(p.name)}"><span><h3>${esc(p.name)}</h3><p class="patient-card-meta"><span>${outlineIcon('user')} Age: ${esc(p.age||'Not set')}</span><i></i><span>${outlineIcon('location')} ${esc(p.city||'Location not set')}</span></p><span class="chip connection-chip ${p.status==='active'?'good':'warn'}">${p.status==='active'?'Account connected':'Awaiting signup'}</span></span><span class="open-arrow">›</span></button><button class="patient-card-delete" onclick="deletePatientDashboard('${p.id}')" aria-label="Delete ${esc(p.name)} patient profile" title="Delete patient profile">${outlineIcon('trash')}</button></div>`).join(''):'<div class="card empty"><p>Create your first patient dashboard.</p></div>'}</div></section><section><div class="section-title"><h2>Patient Conversations</h2><span class="chip warn">${unread} new</span></div><div class="stack">${conversationPatients.length?conversationPatients.map(p=>patientConversation(p,notes)).join(''):'<div class="card empty compact-empty"><p>No patient conversations yet.</p></div>'}</div></section>`,'caregiver',true)}
async function replyToPatient(ev,patientId){ev.preventDefault();let input=ev.target.elements.message,message=input.value.trim();if(!message)return;input.disabled=true;try{await CareFirebase.replyToPatient(patientId,message);toast('Reply sent and messages marked as read');await loadCaretakerOverview()}catch(e){input.disabled=false;operationFailed(e)}}
async function loadCaretakerOverview(){if(state.overviewLoading)return;state.overviewLoading=true;try{let patients=await CareFirebase.caretakerPatients(),groups=await Promise.all(patients.filter(p=>p.patientId).map(async p=>(await CareFirebase.loadPatientNotifications(p.patientId)).map(n=>({...n,patientName:p.name,patientPhoto:p.photoUrl||p.defaultAvatar,patientId:p.patientId}))));store.set('caretakerPatients',patients);store.set('careNotifications',groups.flat().sort((a,b)=>String(b.timestamp||b.createdAt?.seconds||'').localeCompare(String(a.timestamp||a.createdAt?.seconds||''))));state.overviewLoadedAt=Date.now();state.overviewLoading=false;render()}catch(e){state.overviewLoading=false;operationFailed(e)}}
function patientNotifications(){let p=activePatient(),notes=store.get(patientKey('notifications'),[]);return page(`${back()}${title(`${esc(p?.name||'Patient')} — Messages`,'Notifications sent by this patient.')}<button class="btn btn-primary" onclick="refreshPatientNotifications()">↻ Refresh Messages</button><div class="stack">${notes.length?notes.map(n=>`<div class="card patient-notification"><img class="patient-photo small-photo" src="${p?.photoUrl||p?.defaultAvatar||DEFAULT_WOMAN}" alt=""><div><h3>${esc(p?.name||'Patient')}</h3><p>${esc(n.message)}</p><span class="small muted">${new Date(n.timestamp||Date.now()).toLocaleString()}</span></div></div>`).join(''):'<div class="card empty"><span class="icon">✉</span><h2>No patient messages</h2><p>New messages will appear here.</p></div>'}</div>`,'patients',true)}
async function refreshPatientNotifications(){try{let id=currentPatientId();if(!id)throw new Error('Select a patient first.');let notes=await CareFirebase.loadPatientNotifications(id);store.set(patientKey('notifications'),notes);render()}catch(e){operationFailed(e)}}
function assessmentReports(care=true){let all=store.get(patientKey('assessments'),[]);return page(`${back()}${title('Questionnaire Reports','Every assessment contains nine randomly selected questions for this patient.')}${window.CareFirebase?.configured?'<button class="btn btn-primary" onclick="loadCloudAssessments()">Refresh assessments from Firebase</button>':''}<div class="stack">${all.length?all.map((a,i)=>`<div class="card"><div class="section-title"><h2>Assessment ${all.length-i}</h2><span class="chip">${new Date(a.completedAt||Date.now()).toLocaleDateString()}</span></div><div class="metric"><span>Questions</span><strong>${a.totalQuestions}</strong></div><div class="metric"><span>Support score</span><strong>${a.score}/18</strong></div>${(a.responses||[]).map(r=>`<p class="small"><b>${esc(r.category)}:</b> ${esc(r.question)} — ${esc(r.answer)}</p>`).join('')}</div>`).join(''):`<div class="card empty"><h2>No questionnaire reports yet</h2><p>This patient’s completed assessments will appear here.</p></div>`}</div>`,care?'care-progress':'profile',care)}
async function loadCloudAssessments(){try{let id=currentPatientId();if(!id)throw new Error('Select a patient first.');let data=await CareFirebase.loadAssessments(id);store.set(patientKey('assessments'),data);toast('Patient assessments refreshed');render()}catch(e){operationFailed(e)}}
function relativeDashboard(){let p=activePatient(),name=p?.name||'Linked patient',photo=p?.photoUrl||p?.defaultAvatar||DEFAULT_WOMAN;return page(`${title('Family Support',p?`Shared care view for ${esc(name)}.`:'Your linked patient will appear here.')}<div class="card patient-profile-head patient-showcase-card relative-patient-card"><img src="${photo}" class="patient-photo large-photo" alt="${esc(name)}"><div><h2>${esc(name)}</h2>${p?`<p class="patient-card-meta"><span>${outlineIcon('user')} Age: ${esc(p.age||'Not set')}</span><i></i><span>${outlineIcon('location')} ${esc(p.city||'Location not set')}</span></p><span class="chip connection-chip good">Account connected</span>`:'<p>Ask the caretaker to confirm your patient connection.</p>'}</div></div>${p?`<div class="grid">${featureCard('↗','Shared progress','View this patient’s activity performance.','care-progress')}${featureCard('☷','Questionnaire reports','View this patient’s assessments.','assessment-reports')}${featureCard('◷','Activity history','View individual game sessions.','activity-history')}${featureCard('♥','Family stories','Read familiar stories together.','relative-stories')}${featureCard('☎','Emergency information','View important contacts.','emergency-details')}</div>`:''}<div class="card soft"><p>Relatives have read-only access. Chat deletion and care management remain restricted to the linked caretaker.</p></div>`,'relative-dashboard',true)}
function relativeProfile(){let u=window.CareFirebase?.profile||{};return page(`${title('Relative Profile','Your Manomitra account and linked patient.')}<div class="card account-card"><span class="account-initial large-initial">${esc((u.name||'R')[0].toUpperCase())}</span><div><h2>${esc(u.name||'Relative')}</h2><p>${esc(u.email||window.CareFirebase?.user?.email||'')}</p><span class="chip good">Relative · read-only access</span></div></div><div class="card"><div class="metric"><span>Linked patient</span><strong>${esc(activePatient()?.name||'Not loaded')}</strong></div></div><button class="btn btn-secondary" onclick="logout()">Sign out</button>`,'relative-profile',true)}
function doctorProfile(){let u=window.CareFirebase?.profile||{};return page(`${title('Doctor Profile','Your Manomitra professional account.')}<div class="card account-card"><span class="account-initial large-initial">${esc((u.name||'D')[0].toUpperCase())}</span><div><h2>${esc(u.name||'Doctor')}</h2><p>${esc(u.email||window.CareFirebase?.user?.email||'')}</p></div></div><button class="btn btn-secondary" onclick="logout()">Sign out</button>`,'doctor-profile',true)}
function relativeStories(){return page(`${back()}${title('Family Stories','Read a familiar story together.')}<div class="grid">${memories().map(m=>`<button class="card" onclick="go('memory-detail?id=${m.id}')"><h3>${m.title}</h3><p>${m.story}</p></button>`).join('')}</div>`,'caregiver',true)}
function patientList(health=false){let ps=store.get(health?'assignedPatients':'caretakerPatients',[]);return page(`${title(health?'Assigned Patients':'Patient Dashboards','Patients connected to your account.')}<div class="actions">${!health?'<a class="btn btn-primary" href="#create-patient">＋ Create Patient Dashboard</a>':''}<button class="btn btn-ghost" onclick="${health?'loadAssignedPatients()':'loadCaretakerPatients()'}">Refresh</button></div><div class="stack">${ps.length?ps.map(p=>`<div class="card patient-manage-card patient-showcase-card"><button class="patient-open" onclick="selectPatient('${p.id}')"><img class="patient-photo" src="${p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN}" alt="${esc(p.name)}"><span><h2>${esc(p.name)}</h2><p class="patient-card-meta"><span>${outlineIcon('user')} Age: ${esc(p.age||'Not set')}</span><i></i><span>${outlineIcon('location')} ${esc(p.city||'Location not set')}</span></p><span class="chip connection-chip ${p.status==='active'?'good':'warn'}">${p.status==='active'?'Account connected':'Awaiting signup'}</span></span><span class="open-arrow">›</span></button>${!health?`<button class="patient-card-delete" onclick="deletePatientDashboard('${p.id}')" aria-label="Delete ${esc(p.name)} patient profile" title="Delete patient profile">${outlineIcon('trash')}</button>`:''}</div>`).join(''):'<div class="card empty"><h2>No patient dashboard yet</h2><p>Create a dashboard only when adding a real patient.</p></div>'}</div>`,health?'health':'patients',!health)}
async function deletePatientDashboard(id){let list=store.get('caretakerPatients',[]),patient=list.find(p=>p.id===id);if(!patient)return;if(!confirm(`Delete ${patient.name}'s patient profile? This removes the dashboard and care connections. The Firebase Authentication account, if already created, must be removed separately in Firebase Console.`))return;try{await CareFirebase.deletePatientProfile(patient);store.set('caretakerPatients',list.filter(p=>p.id!==id));if(activePatient()?.id===id){localStorage.removeItem('activePatient');localStorage.removeItem('activePatientPhoto')}toast('Patient profile deleted');render()}catch(e){operationFailed(e)}}
async function loadCaretakerPatients(){try{if(!window.CareFirebase?.configured)return toast('Firebase is not configured.');let ps=await CareFirebase.caretakerPatients();store.set('caretakerPatients',ps);toast('Patient dashboards refreshed');render()}catch(e){toast(e.message)}}
async function loadAssignedPatients(){try{let ps=await CareFirebase.linkedPatientProfiles();store.set('assignedPatients',ps);if(ps.length&&!activePatient())store.set('activePatient',ps[0]);toast('Assigned patients refreshed');render()}catch(e){operationFailed(e)}}
async function selectPatient(id){let p=[...store.get('caretakerPatients',[]),...store.get('assignedPatients',[])].find(x=>x.id===id);if(p?.photoUrl)store.set('activePatientPhoto',p.photoUrl);store.set('activePatient',p);if(p?.patientId&&window.CareFirebase?.configured){let notes=await CareFirebase.loadPatientNotifications(p.patientId).catch(()=>[]);store.set(patientKey('notifications'),notes);let rs=await CareFirebase.loadReminders(p.patientId).catch(()=>[]);store.set(patientKey('reminders'),rs)}go(state.role==='doctor'?'health-patient':p?.status==='active'?'patient-profile':`patient-invite?id=${id}`)}
function patientProfile(health=false){let p=activePatient();if(!p)return empty('Select a patient first',health?'assigned-patients':'patients');return page(`${back()}${title(p.name||'Patient',health?'Doctor care view':'Individual patient management')}<div class="card patient-profile-head"><img src="${p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN}" class="patient-photo large-photo" alt="${esc(p.name)}"><div><h2>${esc(p.name)}</h2><p class="patient-card-meta"><span>${outlineIcon('user')} Age: ${esc(p.age||'Not set')}</span><i></i><span>${outlineIcon('location')} ${esc(p.city||'Location not set')}</span></p><span class="chip connection-chip ${p.status==='active'?'good':'warn'}">${p.status}</span></div></div>${!health?`<a class="btn btn-secondary" href="#create-doctor?patientId=${encodeURIComponent(p.patientId||'')}">＋ Invite Doctor for this patient</a>`:''}<div class="grid">${featureCard('↗','Game reports & progress','Only this patient’s activity data.',health?'health-trends':'care-progress')}${featureCard('☷','Questionnaire reports','This patient’s saved assessments.','assessment-reports')}${featureCard('◷','Activity history','Scores, attempts, pace and hints.','activity-history')}${featureCard('▣','Reminder monitoring','Completion and missed status.','care-reminders')}${!health?featureCard('⚙','Patient settings','Language, accessibility and activity level.','caretaker-patient-settings'):''}${!health?featureCard('♥','Stories','Manage this patient’s familiar stories.','manage-memories'):''}${!health?featureCard('☎','Emergency details','Contacts, hospital and care notes.','care-emergency'):''}${!health?featureCard('◉','AI chat history','Caretaker-managed conversation history.','care-chat'):''}${featureCard('✉','Patient messages','Messages left by this patient.',health?'health-alerts':'patient-notifications')}${featureCard('!','Care alerts','Reminder and activity alerts.',health?'health-alerts':'alerts')}${featureCard('AI','Care summary','Explainable supportive observations.','ai-summary')}</div>`,health?'health':'patients',!health)}
function activityHistory(){let sessions=store.get(patientKey('sessions'),[]);return page(`${back()}${title('Activity History','Performance details collected for this patient only.')}<div class="table-scroll card">${sessions.length?`<table class="data-table"><thead><tr><th>Activity</th><th>Score</th><th>Accuracy</th><th>Time</th><th>Level</th><th>Attempts</th><th>Hints</th><th>Status</th></tr></thead><tbody>${sessions.map(s=>`<tr><td>${esc(s.type)}</td><td>${s.score??0}</td><td>${s.accuracy??0}%</td><td>${s.time??0}s</td><td>${s.difficulty??'—'}</td><td>${s.attempts??'—'}</td><td>${s.hints??0}</td><td>${esc(s.status||'completed')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty"><h2>No activity reports yet</h2><p>Completed patient games will appear here.</p></div>'}</div>`,'care-progress',true)}
function careReminders(){return reminderList()}
function alerts(health=false){return page(`${title('Alerts & Insights','Only supportive, observable activity information.')}<div class="stack"><div class="card peach alert"><span class="chip warn">Needs Attention</span><h3>Hydration reminder missed</h3><p>10:30 AM · Prompt shown on the patient device. No completion recorded.</p><button class="btn btn-primary" onclick="toast('Priya and Nurse Lakshmi notified')">Acknowledge & notify care circle</button></div><div class="card"><span class="chip good">Stable</span><h3>Weekly activity performance</h3><p>Four cognitive activity sessions completed. Average pace remains comfortable.</p></div><div class="card soft"><p class="small">These alerts do not indicate diagnosis or disease progression. Use clinical judgment and direct assessment for healthcare decisions.</p></div></div>`,health?'health-alerts':'alerts',!health)}
function aiSummary(){return page(`${back()}${title('AI Care Summary','Explainable observations for supportive action.')}<div class="card mint"><h2>This week at a glance</h2><p>Kalyani completed 4 of 5 suggested activities. Familiar music and family-photo activities led to longer, calm engagement. One hydration reminder was missed.</p></div><div class="card"><h2>Suggested caregiver actions</h2><p>• Continue photo-based recall at the current gentle level.</p><p>• Offer a voice hydration reminder near 10:30 AM.</p><p>• Keep sessions around 5–10 minutes, with breaks.</p></div><div class="card soft"><h3>How this was generated</h3><p>CareLoop used completion status, activity accuracy, response time, hints, reminder status and recent engagement. It did not infer a diagnosis.</p></div><button class="btn btn-secondary" onclick="window.print()">▣ Download / Print doctor visit summary</button>`,'caregiver',true)}
function careSettings(){let u=window.CareFirebase?.profile||{};return page(`${title('Caretaker Settings','Account, sharing and privacy.')}<div class="card account-card"><span class="account-initial large-initial">${esc((u.name||'C')[0].toUpperCase())}</span><div><h2>${esc(u.name||'Caretaker')}</h2><p>${esc(u.email||window.CareFirebase?.user?.email||'')}</p><span class="chip good">Caretaker account</span></div></div><div class="card"><div class="metric"><span>Hydration alerts</span><button class="toggle on" onclick="this.classList.toggle('on')"></button></div><div class="metric"><span>Medicine alerts</span><button class="toggle on" onclick="this.classList.toggle('on')"></button></div><div class="metric"><span>Weekly AI summary</span><button class="toggle on" onclick="this.classList.toggle('on')"></button></div></div><button class="btn btn-secondary" onclick="logout()">Sign out</button>`,'care-settings',true)}
function caregiverProfile(){return careSettings()}

function healthDashboard(){return page(`${title('Healthcare Worker Dashboard','Lakshmi M. · ASHA · Supportive care view')}<div class="stat-grid"><div class="stat"><span>Assigned patients</span><b>1</b></div><div class="stat"><span>Needs attention</span><b>1</b></div><div class="stat"><span>Check-ins today</span><b>1</b></div><div class="stat"><span>Sync</span><b>Current</b></div></div><div class="grid">${featureCard('♙','Assigned patients','Review connected patient profiles.','assigned-patients')}${featureCard('!','Alerts and insights','Supportive follow-up items.','health-alerts')}</div><div class="card"><h2>Today’s check-in</h2><p><b>Kalyani Amma</b> · Blood pressure 126/82, pulse 74 bpm · values entered for visit context.</p><button class="btn btn-primary" onclick="go('health-patient')">Open patient details</button></div><p class="small muted">CareLoop trends support care coordination and are not diagnostic conclusions.</p>`,'health',true)}

function empty(msg,route='home'){return page(`<div class="empty"><span class="icon">○</span><h1>${msg}</h1><p class="muted">There is nothing to show here yet.</p><button class="btn btn-primary" onclick="go('${route}')">Go back</button></div>`,route)}
function notFound(){return publicPage(`${title('Page not found','The link may be old or incomplete.')}<button class="btn btn-primary" onclick="go('${state.role==='caregiver'?'caregiver':state.role==='health'?'health':'home'}')">Return to dashboard</button>`)}
async function logout(){if(window.CareFirebase?.configured)await CareFirebase.signOut().catch(()=>{});sessionStorage.removeItem('careloopSession');authenticated=false;localStorage.removeItem('role');state.role='patient';go('login')}

const routes={welcome,login:()=>login(),signup:()=>login(true),forgot,role,language,'patient-setup':patientSetup,'caregiver-setup':caregiverSetup,questionnaire,'questionnaire-result':qResult,home,games,'game-intro':p=>gameIntro(p.type),play,'game-result':gameResult,progress:()=>progress(false),chat,'chat-history':()=>chatHistory(false),reminders:reminderList,'add-reminder':()=>reminderForm(false),'edit-reminder':p=>reminderForm(true,p.id),'reminder-detail':p=>reminderDetail(p.id),memories:()=>memoryList(false),'add-memory':addMemory,'memory-detail':p=>memoryDetail(p.id),profile,'patient-message':patientMessage,'patient-questionnaire':questionnaireHub,'my-assessment-reports':patientAssessmentReports,'care-circle':careCircle,'emergency-details':()=>emergencyDetails(false),settings,'language-settings':()=>language(true),'notification-settings':notificationSettings,help,sync:syncPage,caregiver,'relative-dashboard':relativeDashboard,'relative-profile':relativeProfile,'relative-stories':relativeStories,patients:()=>patientList(false),'patient-profile':()=>patientProfile(false),'patient-notifications':patientNotifications,'care-progress':()=>progress(true),'assessment-reports':assessmentReports,'activity-history':activityHistory,'care-reminders':careReminders,'care-emergency':()=>emergencyDetails(true),'care-chat':()=>chatHistory(true),alerts:()=>alerts(false),'ai-summary':aiSummary,'manage-memories':()=>memoryList(true),'care-settings':careSettings,'caregiver-profile':caregiverProfile,'doctor-profile':doctorProfile,'health-login':()=>login(false,true),health:healthDashboard,'assigned-patients':()=>patientList(true),'health-patient':()=>patientProfile(true),'health-trends':()=>progress(true),'health-alerts':()=>alerts(true)};
routes['patient-signup']=patientSignup;
routes['caretaker-signup']=()=>registration('caretaker');routes['relative-signup']=()=>registration('relative');routes['doctor-signup']=()=>registration('doctor');
routes['create-patient']=createPatient;routes['create-doctor']=p=>createRelative('doctor',p.patientId||'');routes['patient-invite']=p=>patientInvite(p.id);routes['create-relative']=p=>createRelative('relative',p.patientId||'');routes['relative-invite']=relativeInvite;routes['caretaker-patient-settings']=caretakerPatientSettings;
function parseHash(){let raw=(location.hash.slice(1)||'login').split('?'),p=Object.fromEntries(new URLSearchParams(raw[1]||''));return {route:raw[0],p}}
const publicRoutes=new Set(['welcome','login','role','signup','patient-signup','caretaker-signup','relative-signup','doctor-signup','forgot']);
const caretakerOnly=new Set(['caregiver','patients','create-patient','patient-invite','create-relative','create-doctor','relative-invite','patient-profile','patient-notifications','caretaker-patient-settings','care-reminders','care-chat','care-settings','caregiver-profile','manage-memories','care-emergency','alerts']);
const relativeOnly=new Set(['relative-dashboard','relative-profile','relative-stories']);
const doctorOnly=new Set(['health','assigned-patients','health-patient','health-trends','health-alerts','doctor-profile']);
const patientOnly=new Set(['home','games','game-intro','play','game-result','chat','chat-history','reminders','profile','patient-message','patient-questionnaire','my-assessment-reports','questionnaire','questionnaire-result','memories','add-memory','memory-detail','settings','language-settings','notification-settings','help','sync','care-circle']);
function dashboardForRole(){return state.role==='caretaker'?'caregiver':state.role==='doctor'?'health':state.role==='relative'?'relative-dashboard':'home'}
function render(){let {route,p}=parseHash();if(!publicRoutes.has(route)){if(!authResolved){document.querySelector('#app').innerHTML=publicPage('<div class="center"><div class="loader"></div><h2>Checking secure login…</h2></div>');return}if(!authenticated){location.hash='login';return}if((caretakerOnly.has(route)&&state.role!=='caretaker')||(relativeOnly.has(route)&&state.role!=='relative')||(doctorOnly.has(route)&&state.role!=='doctor')||(patientOnly.has(route)&&state.role!=='patient')){state.operationError='';state.operationErrorRoute='';location.hash=dashboardForRole();return}}let markup=(routes[route]||notFound)(p).replaceAll('CareLoop','Manomitra');document.querySelector('#app').innerHTML=markup;if(route==='caregiver'&&window.CareFirebase?.configured&&!state.overviewLoading&&Date.now()-state.overviewLoadedAt>15000)setTimeout(loadCaretakerOverview,0);document.title=`${route.replace(/-/g,' ')} · Manomitra`;scrollTo(0,0)}
window.addEventListener('care-firebase-auth',async e=>{authResolved=true;authenticated=!!e.detail.user;if(e.detail.profile){state.role=e.detail.profile.role;store.set('role',state.role);let p=null;if(state.role==='patient'&&window.CareFirebase?.loadOwnPatientProfile)p=await CareFirebase.loadOwnPatientProfile().catch(()=>null);else if(['relative','doctor'].includes(state.role)&&e.detail.profile.patientId)p=await CareFirebase.loadPatientProfile(e.detail.profile.patientId).catch(()=>null);if(p){if(state.role==='patient')store.set('profile',p);store.set('activePatient',p);store.set('activePatientPhoto',p.photoUrl||p.defaultAvatar||DEFAULT_WOMAN);if(window.CareFirebase?.configured){let rs=await CareFirebase.loadReminders(p.patientId||e.detail.user?.uid).catch(()=>[]);store.set(patientKey('reminders'),rs)}}}render()});
window.addEventListener('hashchange',render);window.addEventListener('online',()=>{document.querySelector('#offlineBanner')?.setAttribute('hidden','');syncNow()});window.addEventListener('offline',()=>{document.querySelector('#offlineBanner')?.removeAttribute('hidden');toast('Offline mode · your work is safe')});
setTimeout(checkDueReminders,1000);setInterval(checkDueReminders,20000);setInterval(()=>{if(parseHash().route==='caregiver'&&authenticated&&window.CareFirebase?.configured&&Date.now()-state.overviewLoadedAt>=15000)loadCaretakerOverview()},15000);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(reg=>reg.update()).catch(()=>{}));
let offlineBanner=document.querySelector('#offlineBanner');if(offlineBanner)offlineBanner.hidden=navigator.onLine;render();














