window.QUESTION_BANK = [
 {id:'m1',category:'Memory',text:'How easy is it to remember something you heard a few minutes ago?',options:['Usually easy','Sometimes difficult','Often difficult']},
 {id:'m2',category:'Memory',text:'How often do you remember where you placed familiar things?',options:['Most times','Sometimes','I often need help']},
 {id:'m3',category:'Memory',text:'Can you remember the main events from yesterday?',options:['Clearly','Some events','Very few events']},
 {id:'m4',category:'Memory',text:'How easy is it to remember familiar names?',options:['Usually easy','Sometimes difficult','Often difficult']},
 {id:'m5',category:'Memory',text:'Do reminders help you complete planned tasks?',options:['Rarely needed','Sometimes helpful','Often needed']},
 {id:'m6',category:'Memory',text:'How easy is it to follow a short story?',options:['Easy','Sometimes difficult','Very difficult']},
 {id:'a1',category:'Attention',text:'How comfortable is it to focus on one activity for 10 minutes?',options:['Comfortable','Sometimes difficult','Very difficult']},
 {id:'a2',category:'Attention',text:'Can you finish a simple activity without becoming distracted?',options:['Usually','Sometimes','Rarely']},
 {id:'a3',category:'Attention',text:'How easy is it to follow a conversation with two people?',options:['Easy','Sometimes difficult','Very difficult']},
 {id:'a4',category:'Attention',text:'Can you find an item you are looking for in a familiar room?',options:['Usually','With some time','I need help']},
 {id:'a5',category:'Attention',text:'How comfortable are you with matching pictures or shapes?',options:['Comfortable','Sometimes difficult','Very difficult']},
 {id:'a6',category:'Attention',text:'Can you return to an activity after a short interruption?',options:['Usually','Sometimes','Rarely']},
 {id:'r1',category:'Daily routine',text:'How often do you remember your usual morning routine?',options:['Most days','Some days','I need reminders']},
 {id:'r2',category:'Daily routine',text:'Can you choose suitable clothes for the day?',options:['Independently','With a little help','I need help']},
 {id:'r3',category:'Daily routine',text:'How easy is it to prepare a familiar drink or snack?',options:['Easy','With some help','Very difficult']},
 {id:'r4',category:'Daily routine',text:'Do you remember your usual meal times?',options:['Most days','Some days','I need reminders']},
 {id:'r5',category:'Daily routine',text:'Can you follow two simple steps in order?',options:['Usually','Sometimes','I need help']},
 {id:'r6',category:'Daily routine',text:'How often do you know what part of the day it is?',options:['Most times','Sometimes','Rarely']},
 {id:'w1',category:'Well-being',text:'How have you been feeling this week?',options:['Calm and positive','A little worried','Low or unsettled']},
 {id:'w2',category:'Well-being',text:'Have familiar activities felt enjoyable recently?',options:['Often','Sometimes','Rarely']},
 {id:'w3',category:'Well-being',text:'How comfortable do you feel asking family for help?',options:['Comfortable','Sometimes unsure','Uncomfortable']},
 {id:'w4',category:'Well-being',text:'How restful has your sleep felt?',options:['Restful','Somewhat restless','Often restless']},
 {id:'w5',category:'Well-being',text:'How often have you felt lonely this week?',options:['Rarely','Sometimes','Often']},
 {id:'w6',category:'Well-being',text:'Do calm music or familiar stories help you relax?',options:['Often','Sometimes','Rarely']},
 {id:'f1',category:'Recognition',text:'How easy is it to recognize familiar people?',options:['Usually easy','Sometimes difficult','Often difficult']},
 {id:'f2',category:'Recognition',text:'How easy is it to recognize familiar household objects?',options:['Usually easy','Sometimes difficult','Often difficult']},
 {id:'f3',category:'Recognition',text:'Can you recognize familiar places in photographs?',options:['Usually','Sometimes','Rarely']},
 {id:'f4',category:'Recognition',text:'How easily do familiar songs come to mind?',options:['Easily','With a prompt','Rarely']},
 {id:'f5',category:'Recognition',text:'Can you identify close family members by voice?',options:['Usually','Sometimes','Rarely']},
 {id:'f6',category:'Recognition',text:'How easy is it to recognize your daily medicines by their container?',options:['Usually easy','Sometimes difficult','I need assistance']}
];
